# Generated by Django 4.2.7 on 2025-07-24 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_alone', models.FloatField(default=0)),
                ('stage_fear', models.CharField(default='No', max_length=10)),
                ('social_event_attendance', models.FloatField(default=0)),
                ('going_outside', models.FloatField(default=0)),
                ('drained_after_socializing', models.CharField(default='No', max_length=10)),
                ('friends_circle_size', models.FloatField(default=0)),
                ('post_frequency', models.FloatField(default=0)),
                ('personality', models.CharField(max_length=20)),
                ('feature_data', models.JSONField(blank=True, default=dict)),
                ('target_value', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personality Data',
                'verbose_name_plural': 'Personality Data',
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('svm', 'Support Vector Machine'), ('neural_network', 'Neural Network')], max_length=20)),
                ('model_file', models.FileField(upload_to='models/')),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('training_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trained Model',
                'verbose_name_plural': 'Trained Models',
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_features', models.JSONField(default=dict)),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('probabilities', models.JSONField(default=dict)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_app.trainedmodel')),
            ],
            options={
                'verbose_name': 'Prediction Result',
                'verbose_name_plural': 'Prediction Results',
            },
        ),
    ]
